pipeline {
    agent any
    stages {
        stage ('Checkout') {
            steps {
                echo 'checking out source code ...'
                checkout scm
            }
         }

        stage ('installing dependencies') {
            steps {
                echo 'installing python dependencies ...'
                sh '''
                    python3 -m venv venv
                    ./venv/bin/pip install --upgrade pip
                    ./venv/bin/pip install -r requirements.txt
                   
                '''                
            }
         }

        stage ('Test') {
            steps {
                echo 'running test ...'
                sh '''
                    ./venv/bin/pytest -V
                '''
            }
         }

         stage ('deploy') {
             steps {
                 echo 'deploying python applicaltion...'
                 sh ''' 
                     pkill -f "python.*app.py" || true
                     nohup ./venv/bin/python app.py > app.log 2>&1 &
                     sleep 3
                     curl -f http://localhost:5000/health
                 '''
             }
         }
     }
     post {
        success {
            echo 'CI/CD Pipeline completed successfully!'
        }

        failure {
            echo 'CI/CD Pipeline failed!'
        }
    }
}
